# Makefile for Wii-specific code

CXXFLAGS	+= -DWII -DHW_RVL -DUSE_EXPANSION -D__wii__

LDFLAGS		+= -mrvl

LIBOGC2_INCLUDE 	?= $(firstword $(wildcard $(DEVKITPRO)/libogc2/include) $(wildcard $(DEVKITPRO)/libogc2/wii/include))
LIBOGC2_WII_LIB 	?= $(firstword $(wildcard $(DEVKITPRO)/libogc2/lib/wii) $(wildcard $(DEVKITPRO)/libogc2/wii/lib))

LIBPATHS 	+= -L$(LIBOGC2_WII_LIB)
INCLUDE 	+= -I$(LIBOGC2_INCLUDE)

OBJ		+= \
		vm/dsihandler.o \
		vm/wii_vm.o \
		vm/pagefile.o \
		main/wii.o \
		main/Autoboot.o

OBJ_INPUT	+= \
		gc_input/controller-Classic.o \
		gc_input/controller-WiimoteNunchuk.o

LIB		+= -lwiiuse -lbte -lz

# External HBC-Reborn SDK; opt-in development builds only.
ifeq ($(HBC_AGENT),1)
HBC_AGENT_ROOT ?= ../hbc-reborn
FEATURES += -DWII64_HBC_AGENT
INCLUDE += -I"$(HBC_AGENT_ROOT)/sdk"
LIBPATHS += -L"$(HBC_AGENT_ROOT)/sdk/hbc_agent/libogc2"
LIB := -lhbcagent $(LIB)
OBJ += main/dev_agent.o
endif
