# Makefile for GC-specific code

CXXFLAGS	+= -DHW_DOL -DUSE_TLB_CACHE -DTINY_TLBCACHE -D__gamecube__

LDFLAGS		+= -mogc

LIBPATHS	+= -L$(DEVKITPRO)/libogc2/lib/cube
INCLUDE 	+= -I$(DEVKITPRO)/libogc2/include

OBJ		+= \
		gc_memory/TLB-Cache.o \
		vm/vm.o \
		vm/dsihandler.o

LIB		+= -lz

