#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)
WIZARD_PROGRESS="${WIZARD_PROGRESS:-auto}" # auto | off | force
_PV_UNAVAILABLE_WARNED=0

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# pv_stream LABEL SIZE copies stdin to stdout while showing byte-accurate
# progress when pv is installed. SIZE must be a numeric byte total. Status is
# always written to stderr, so using this in a data pipeline never corrupts
# stdout. Set WIZARD_PROGRESS=off to disable it, or force to show it when
# stderr is not a terminal.
pv_stream() {
  local label="$1" size="$2"
  if [[ ! "$size" =~ ^[0-9]+$ ]]; then
    printf '  %s⚠ progress unavailable for %s: no numeric byte total%s\n' "$YELLOW" "$label" "$RESET" >&2
    cat
    return
  fi
  if [[ "$WIZARD_PROGRESS" == off ]]; then
    cat
    return
  fi
  if ! command -v pv >/dev/null 2>&1; then
    if (( ! _PV_UNAVAILABLE_WARNED )); then
      printf '  %s⚠ pv is unavailable; continuing without stream progress%s\n' "$YELLOW" "$RESET" >&2
      _PV_UNAVAILABLE_WARNED=1
    fi
    cat
    return
  fi
  case "$WIZARD_PROGRESS" in
    auto|force) ;;
    *) printf 'WIZARD_PROGRESS must be auto, off, or force (got %q)\n' "$WIZARD_PROGRESS" >&2; return 2 ;;
  esac
  local -a args=(--wait --delay-start 2 --interval 1 --name "$label" --size "$size" --progress --timer --eta --rate --average-rate --bytes)
  [[ "$WIZARD_PROGRESS" == force ]] && args+=(--force)
  pv "${args[@]}"
}

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Wii hardware setup. Keep the library above unchanged.
TOTAL_STAGES=3
# Codex/macOS terminals can report "dumb"; tput clear then exits before banner.
if [[ "${TERM:-}" == dumb || -z "${TERM:-}" ]]; then export TERM=xterm; fi
cd "$(dirname "${BASH_SOURCE[0]}")/.."
ENV_FILE="$PWD/.dev/hardware.env"
banner "Wii64 hardware testing"

stage "Wii address"
step "Turn on the Wii and open Homebrew Channel. Find its LAN IPv4 address."
ask WII64_WII_IP "Wii IPv4 address:"
python3 -c 'import ipaddress,sys; ipaddress.IPv4Address(sys.argv[1])' "$WII64_WII_IP"
write_env WII64_WII_IP "$WII64_WII_IP"

stage "SD card and test ROMs"
step "Insert the Wii SD card into this computer. Keep a backup of any important card data."
ask WII64_SD_ROOT "Mounted SD card root (for example /Volumes/WII):"
[[ -d "$WII64_SD_ROOT" && "$WII64_SD_ROOT" != / && "$WII64_SD_ROOT" != . && "$WII64_SD_ROOT" != "$PWD" ]] || { warn "Use the mounted SD card root."; exit 1; }
ask WII64_CHAIN "Test chain (smoke or hardware):"
case "$WII64_CHAIN" in smoke|hardware) ;; *) warn "Choose smoke or hardware."; exit 1 ;; esac
say "The selected chain needs these legally obtained ROMs at sd:/wii64/roms/:"
sed -n 's/^chain=[^ ]* sd:\/wii64\/roms\///p' "scripts/chains/$WII64_CHAIN.txt" | sort -u | sed 's/^/  /'
step "Copy those ROMs to $WII64_SD_ROOT/wii64/roms/ with the exact names shown."
pause "Press Enter after the files are in place."
missing=0
while IFS= read -r rom; do
  [[ -f "$WII64_SD_ROOT/wii64/roms/$rom" ]] || { warn "Missing: $rom"; missing=1; }
done < <(sed -n 's/^chain=[^ ]* sd:\/wii64\/roms\///p' "scripts/chains/$WII64_CHAIN.txt" | sort -u)
(( missing == 0 )) || exit 1
write_env WII64_SD_ROOT "$WII64_SD_ROOT"
write_env WII64_CHAIN "$WII64_CHAIN"

stage "Mac result address"
step "Find this computer's LAN IPv4 address on the same network as the Wii."
if [[ "$(uname -s)" == Darwin ]]; then
  iface=$(route -n get "$WII64_WII_IP" 2>/dev/null | awk '/interface:/{print $2; exit}')
  [[ -n "$iface" ]] && say "Likely address: $(ipconfig getifaddr "$iface" 2>/dev/null || true)"
fi
ask WII64_MAC_IP "This computer's LAN IPv4 address:"
python3 -c 'import ipaddress,socket,sys; ipaddress.IPv4Address(sys.argv[1]); s=socket.socket(); s.bind((sys.argv[1],0)); s.close()' "$WII64_MAC_IP"
say "I will write $WII64_SD_ROOT/wii64/diag.cfg for $WII64_CHAIN and result_host=$WII64_MAC_IP."
confirm "Write the test configuration to this SD card?" || exit 1
mkdir -p "$WII64_SD_ROOT/wii64"
mkdir -p "$WII64_SD_ROOT/wii64/input"
cp -p scripts/inputs/*.txt "$WII64_SD_ROOT/wii64/input/"
if [[ -f "$WII64_SD_ROOT/wii64/diag.cfg" ]]; then
  cp -p "$WII64_SD_ROOT/wii64/diag.cfg" "$WII64_SD_ROOT/wii64/diag.cfg.before-hardware-$(date +%Y%m%d%H%M%S)"
fi
{ sed '/^[[:space:]]*#/d; /^[[:space:]]*$/d' "scripts/chains/$WII64_CHAIN.txt"; printf 'result_host=%s\n' "$WII64_MAC_IP"; } > "$WII64_SD_ROOT/wii64/diag.cfg"
write_env WII64_MAC_IP "$WII64_MAC_IP"
step "Eject the SD card, insert it into the Wii, and leave Homebrew Channel open."
say "Then run: .dev/hardware_run.sh"
finish
